# Generated by Django 3.2.5 on 2021-07-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_applied', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.TextField(blank=True, null=True)),
                ('lnk', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobSearchFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_filter_name', models.TextField(blank=True, null=True, unique=True)),
                ('with_all_of_these_words', models.TextField(blank=True, null=True)),
                ('with_the_exact_phrase', models.TextField(blank=True, null=True)),
                ('with_at_least_one_of_these_words', models.TextField(blank=True, null=True)),
                ('with_none_of_these_words', models.TextField(blank=True, null=True)),
                ('with_these_words_in_the_title', models.TextField(blank=True, null=True)),
                ('from_this_company', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
